[workspace]
members = [
    "bin",
    "program",
]
resolver = "2"

[workspace.dependencies]
solana-client = "2.1.0"
solana-program = "2.1.0"
solana-sdk = "2.1.0"
solana-test-validator = "2.1.0"
tokio = "1.37.0"
